_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 30 # prevents early stopping
max_epochs: 50

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# reload the train dataloader every N epoch
reload_dataloaders_every_n_epochs: 1

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# log every N steps
log_every_n_steps: 20
# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
