defaults:
  - _seg_default

net:
  _target_: src.models.components.DeepLab_resnet50.DeepLabResnet50
  img_size: ${data.imagesize}
  pretrained: True
  pretrained_path: datasets/Models/resnet50-11ad3fa6.pth

