defaults:
  - _seg_default

net:
  _target_: src.models.components.timmNet.timmNet
  backbone: "swin_small_patch4_window7_224"
  pretrained: True
  pretrained_path: datasets/Models/swin_small_patch4_window7_224.ms_in22k.bin
  segmentation_head:
    _partial_: True
    _target_: src.models.components.utils.SimpleSegmentationHead #src.models.components.utils.SimpleSegmentationHead
    decoder_stride: 32

