defaults:
  - ViT_S

net:
  ViT_patch_size: 16
  ViT_embed_dim: 512
  ViT_depth: 12
  ViT_num_heads: 8
  ViT_mlp_ratio: 4.0
  pretrained_encoder_path: datasets/Models/deit_3_medium_224_21k.pth #patchsize 16
