defaults:
  - _seg_default

net:
  _target_: src.models.components.ViT.ViT
  embedder:
    _partial_: true
    _target_: src.models.components.ViT.LinearEmbedding
  ViT_patch_size: 16
  ViT_embed_dim: 384
  ViT_depth: 12
  ViT_num_heads: 6
  ViT_mlp_ratio: 4.0
  decoder_stride: ${model.net.ViT_patch_size}
  pretrained_encoder: True
  pretrained_encoder_path: datasets/Models/deit_3_small_224_21k.pth #patchsize 16
  pretrained_encoder_inter: True
